# Generated by https://smithery.ai. See: https://smithery.ai/docs/build/project-config
# Dockerfile for MCP Fathom Analytics Server
FROM node:lts-alpine AS builder
WORKDIR /app
# Install dependencies and build
COPY package.json package-lock.json tsconfig.json postbuild.js ./
COPY src ./src
RUN npm install --production --ignore-scripts && \
    npm install --save-dev typescript @types/node && \
    npm run build

# Runtime image
FROM node:lts-alpine
WORKDIR /app
# Copy built artifacts and production dependencies
COPY --from=builder /app/dist ./dist
COPY package.json package-lock.json ./
RUN npm install --production --ignore-scripts

# Set default command
CMD ["node", "dist/index.js"]
